# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'Group 5 Prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: [ '127.0.0.1:9090' ]

  - job_name: 'Group 5 spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
#      - targets: [ 'HOST_IP:8080' ]
#      - targets: [ '10.10.15.71:8080' ]
      - targets: [ '172.19.140.41:8080' ]

# Prometheus File for docker run
# "/Users/alvinabaho/Google Drive/ALVIN EDUCATION/COMPRO/7. EA/LABS/SpringStarterProject/src/main/resources/prometheus.yml"
# docker run -d --name=prometheus -p 9090:9090 -v <PATH_TO_prometheus.yml_FILE>:/etc/prometheus/prometheus.yml prom/prometheus --config.file=/etc/prometheus/prometheus.yml
# docker run -d --name=prometheus -p 9090:9090 -v "/Users/alvinabaho/Google Drive/ALVIN EDUCATION/COMPRO/7. EA/LABS/SpringStarterProject/src/main/resources/prometheus.yml":/etc/prometheus/prometheus.yml prom/prometheus --config.file=/etc/prometheus/prometheus.yml
# docker run -d --name=prometheus -p 9090:9090 -v "/Users/alvinabaho/Google Drive/ALVIN EDUCATION/COMPRO/7. EA/PROJECT/MAIN/flight-reservation-g5/src/main/resources/prometheus.yml":/etc/prometheus/prometheus.yml prom/prometheus --config.file=/etc/prometheus/prometheus.yml